apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
    spec:
  containers:
    - name: catalogue
      imagePullPolicy: Always
      Image: klkreddy123/catalogue:v1
      resoruces:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue # label should be used to identify for connection
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080        