---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
    - name: mongodb
      imagePullPolicy: Always
      Image: klkreddy123/mongodb:v1
      resoruces:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb # label should be used to identify for connection
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017        